language: minimal

services:
  - docker

cache:
  directories:
    - build/cache

before_script:
  - scripts/ci/docker-image.sh tryload plainkv-builder:latest

script:
  - make USE_DOCKER=1

before_cache:
  - scripts/ci/docker-image.sh trysave plainkv-builder:latest

after_success:
  - bash <(curl -s https://codecov.io/bash)
