// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/roy2220/plainkv/hashmap/internal/protocol/hashmap.proto

package protocol

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type HashMapInfo struct {
	SlotDirsAddr         int64 `protobuf:"varint,1,opt,name=slot_dirs_addr,json=slotDirsAddr,proto3" json:"slot_dirs_addr,omitempty"`
	SlotDirCount         int64 `protobuf:"varint,2,opt,name=slot_dir_count,json=slotDirCount,proto3" json:"slot_dir_count,omitempty"`
	MaxSlotDirCountShift int64 `protobuf:"varint,3,opt,name=max_slot_dir_count_shift,json=maxSlotDirCountShift,proto3" json:"max_slot_dir_count_shift,omitempty"`
	SlotCount            int64 `protobuf:"varint,4,opt,name=slot_count,json=slotCount,proto3" json:"slot_count,omitempty"`
	MinSlotCountShift    int64 `protobuf:"varint,5,opt,name=min_slot_count_shift,json=minSlotCountShift,proto3" json:"min_slot_count_shift,omitempty"`
	ItemCount            int64 `protobuf:"varint,6,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	PayloadSize          int64 `protobuf:"varint,7,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
}

func (m *HashMapInfo) Reset()         { *m = HashMapInfo{} }
func (m *HashMapInfo) String() string { return proto.CompactTextString(m) }
func (*HashMapInfo) ProtoMessage()    {}
func (*HashMapInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1b7cb7734b5569, []int{0}
}
func (m *HashMapInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashMapInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashMapInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashMapInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashMapInfo.Merge(m, src)
}
func (m *HashMapInfo) XXX_Size() int {
	return m.Size()
}
func (m *HashMapInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HashMapInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HashMapInfo proto.InternalMessageInfo

func (m *HashMapInfo) GetSlotDirsAddr() int64 {
	if m != nil {
		return m.SlotDirsAddr
	}
	return 0
}

func (m *HashMapInfo) GetSlotDirCount() int64 {
	if m != nil {
		return m.SlotDirCount
	}
	return 0
}

func (m *HashMapInfo) GetMaxSlotDirCountShift() int64 {
	if m != nil {
		return m.MaxSlotDirCountShift
	}
	return 0
}

func (m *HashMapInfo) GetSlotCount() int64 {
	if m != nil {
		return m.SlotCount
	}
	return 0
}

func (m *HashMapInfo) GetMinSlotCountShift() int64 {
	if m != nil {
		return m.MinSlotCountShift
	}
	return 0
}

func (m *HashMapInfo) GetItemCount() int64 {
	if m != nil {
		return m.ItemCount
	}
	return 0
}

func (m *HashMapInfo) GetPayloadSize() int64 {
	if m != nil {
		return m.PayloadSize
	}
	return 0
}

type HashSlot struct {
	ItemInfos []HashItemInfo `protobuf:"bytes,1,rep,name=item_infos,json=itemInfos,proto3" json:"item_infos"`
	Bin       BytesView      `protobuf:"bytes,2,opt,name=bin,proto3,customtype=BytesView" json:"bin"`
}

func (m *HashSlot) Reset()         { *m = HashSlot{} }
func (m *HashSlot) String() string { return proto.CompactTextString(m) }
func (*HashSlot) ProtoMessage()    {}
func (*HashSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1b7cb7734b5569, []int{1}
}
func (m *HashSlot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashSlot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashSlot.Merge(m, src)
}
func (m *HashSlot) XXX_Size() int {
	return m.Size()
}
func (m *HashSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_HashSlot.DiscardUnknown(m)
}

var xxx_messageInfo_HashSlot proto.InternalMessageInfo

func (m *HashSlot) GetItemInfos() []HashItemInfo {
	if m != nil {
		return m.ItemInfos
	}
	return nil
}

type HashItemInfo struct {
	KeySum    uint64 `protobuf:"fixed64,1,opt,name=key_sum,json=keySum,proto3" json:"key_sum,omitempty"`
	KeySize   int64  `protobuf:"varint,2,opt,name=key_size,json=keySize,proto3" json:"key_size,omitempty"`
	ValueSize int64  `protobuf:"varint,3,opt,name=value_size,json=valueSize,proto3" json:"value_size,omitempty"`
}

func (m *HashItemInfo) Reset()         { *m = HashItemInfo{} }
func (m *HashItemInfo) String() string { return proto.CompactTextString(m) }
func (*HashItemInfo) ProtoMessage()    {}
func (*HashItemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f1b7cb7734b5569, []int{2}
}
func (m *HashItemInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HashItemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HashItemInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HashItemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashItemInfo.Merge(m, src)
}
func (m *HashItemInfo) XXX_Size() int {
	return m.Size()
}
func (m *HashItemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HashItemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HashItemInfo proto.InternalMessageInfo

func (m *HashItemInfo) GetKeySum() uint64 {
	if m != nil {
		return m.KeySum
	}
	return 0
}

func (m *HashItemInfo) GetKeySize() int64 {
	if m != nil {
		return m.KeySize
	}
	return 0
}

func (m *HashItemInfo) GetValueSize() int64 {
	if m != nil {
		return m.ValueSize
	}
	return 0
}

func init() {
	proto.RegisterType((*HashMapInfo)(nil), "plainkv.HashMapInfo")
	proto.RegisterType((*HashSlot)(nil), "plainkv.HashSlot")
	proto.RegisterType((*HashItemInfo)(nil), "plainkv.HashItemInfo")
}

func init() {
	proto.RegisterFile("github.com/roy2220/plainkv/hashmap/internal/protocol/hashmap.proto", fileDescriptor_0f1b7cb7734b5569)
}

var fileDescriptor_0f1b7cb7734b5569 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x6e, 0xd3, 0x30,
	0x1c, 0xc6, 0x9b, 0x75, 0xb4, 0xab, 0x5b, 0x21, 0xcd, 0x1a, 0x22, 0x20, 0x91, 0x8d, 0xc2, 0x61,
	0x17, 0x1a, 0x54, 0x10, 0x07, 0x6e, 0x04, 0x0e, 0xec, 0x00, 0x87, 0x46, 0xe2, 0xc0, 0xc5, 0x72,
	0x1a, 0xa7, 0xb1, 0x12, 0xdb, 0x51, 0xec, 0x8c, 0x65, 0x4f, 0xc1, 0x3b, 0xf0, 0x32, 0x3b, 0xee,
	0x88, 0x38, 0x4c, 0xa8, 0x7d, 0x11, 0xf4, 0xb7, 0x33, 0xc8, 0xae, 0xdc, 0xfc, 0xff, 0xbe, 0xef,
	0xff, 0x8b, 0xf3, 0x25, 0x28, 0xda, 0x70, 0x93, 0x37, 0xc9, 0x62, 0xad, 0x44, 0x58, 0xab, 0x76,
	0xb9, 0x5c, 0xbe, 0x0c, 0xab, 0x92, 0x72, 0x59, 0x9c, 0x87, 0x39, 0xd5, 0xb9, 0xa0, 0x55, 0xc8,
	0xa5, 0x61, 0xb5, 0xa4, 0x65, 0x58, 0xd5, 0xca, 0xa8, 0xb5, 0x2a, 0x6f, 0x9d, 0x85, 0x15, 0xf0,
	0xb8, 0x5b, 0x78, 0xfc, 0xa2, 0x07, 0xdb, 0xa8, 0x8d, 0x72, 0x0b, 0x49, 0x93, 0xd9, 0xc9, 0x0e,
	0xf6, 0xe4, 0xf6, 0xe6, 0x3f, 0xf6, 0xd0, 0xf4, 0x23, 0xd5, 0xf9, 0x27, 0x5a, 0x9d, 0xc9, 0x4c,
	0xe1, 0xe7, 0xe8, 0xbe, 0x2e, 0x95, 0x21, 0x29, 0xaf, 0x35, 0xa1, 0x69, 0x5a, 0xfb, 0xde, 0x89,
	0x77, 0x3a, 0x5c, 0xcd, 0x40, 0xfd, 0xc0, 0x6b, 0xfd, 0x2e, 0x4d, 0xeb, 0x7e, 0x8a, 0xac, 0x55,
	0x23, 0x8d, 0xbf, 0x77, 0x27, 0xf5, 0x1e, 0x34, 0xfc, 0x06, 0xf9, 0x82, 0x5e, 0x90, 0xbb, 0x49,
	0xa2, 0x73, 0x9e, 0x19, 0x7f, 0x68, 0xf3, 0x47, 0x82, 0x5e, 0xc4, 0xbd, 0x95, 0x18, 0x3c, 0xfc,
	0x04, 0x21, 0xbb, 0xe3, 0xc8, 0xfb, 0x36, 0x39, 0x01, 0xc5, 0x61, 0x43, 0x74, 0x24, 0xb8, 0x24,
	0xff, 0x22, 0x1d, 0xf2, 0x9e, 0x0d, 0x1e, 0x0a, 0x2e, 0xe3, 0xdb, 0xec, 0x5f, 0x1e, 0x37, 0x4c,
	0x74, 0xbc, 0x91, 0xe3, 0x81, 0xe2, 0x78, 0x4f, 0xd1, 0xac, 0xa2, 0x6d, 0xa9, 0x68, 0x4a, 0x34,
	0xbf, 0x64, 0xfe, 0xd8, 0x06, 0xa6, 0x9d, 0x16, 0xf3, 0x4b, 0x36, 0x2f, 0xd0, 0x01, 0x94, 0x04,
	0x5c, 0xfc, 0xb6, 0xa3, 0x71, 0x99, 0x29, 0xed, 0x7b, 0x27, 0xc3, 0xd3, 0xe9, 0xf2, 0xc1, 0xa2,
	0xab, 0x7f, 0x01, 0xb1, 0x33, 0xc3, 0x04, 0x94, 0x19, 0xed, 0x5f, 0xdd, 0x1c, 0x0f, 0xdc, 0xa3,
	0x60, 0xd6, 0xf8, 0x19, 0x1a, 0x26, 0x5c, 0xda, 0xb2, 0x66, 0xd1, 0x21, 0xb8, 0xbf, 0x6e, 0x8e,
	0x27, 0x51, 0x6b, 0x98, 0xfe, 0xc2, 0xd9, 0xb7, 0x15, 0xb8, 0x73, 0x8a, 0x66, 0x7d, 0x0a, 0x7e,
	0x88, 0xc6, 0x05, 0x6b, 0x89, 0x6e, 0x84, 0xfd, 0x16, 0xa3, 0xd5, 0xa8, 0x60, 0x6d, 0xdc, 0x08,
	0xfc, 0x08, 0x1d, 0x58, 0x03, 0x2e, 0xed, 0xfa, 0x87, 0x20, 0x5c, 0x18, 0x5e, 0xf9, 0x9c, 0x96,
	0x0d, 0x73, 0xa6, 0x2b, 0x7b, 0x62, 0x15, 0xb0, 0xa3, 0xcf, 0x57, 0xdb, 0xc0, 0xbb, 0xde, 0x06,
	0xde, 0xef, 0x6d, 0xe0, 0x7d, 0xdf, 0x05, 0x83, 0xeb, 0x5d, 0x30, 0xf8, 0xb9, 0x0b, 0x06, 0x5f,
	0x5f, 0xff, 0xcf, 0xbf, 0x98, 0x8c, 0xec, 0xe9, 0xd5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x11, 0xe0, 0x81, 0xca, 0x02, 0x00, 0x00,
}

func (m *HashMapInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashMapInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashMapInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PayloadSize != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.PayloadSize))
		i--
		dAtA[i] = 0x38
	}
	if m.ItemCount != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.ItemCount))
		i--
		dAtA[i] = 0x30
	}
	if m.MinSlotCountShift != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.MinSlotCountShift))
		i--
		dAtA[i] = 0x28
	}
	if m.SlotCount != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.SlotCount))
		i--
		dAtA[i] = 0x20
	}
	if m.MaxSlotDirCountShift != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.MaxSlotDirCountShift))
		i--
		dAtA[i] = 0x18
	}
	if m.SlotDirCount != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.SlotDirCount))
		i--
		dAtA[i] = 0x10
	}
	if m.SlotDirsAddr != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.SlotDirsAddr))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HashSlot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashSlot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashSlot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Bin.Size()
		i -= size
		if _, err := m.Bin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintHashmap(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ItemInfos) > 0 {
		for iNdEx := len(m.ItemInfos) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ItemInfos[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintHashmap(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *HashItemInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HashItemInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HashItemInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ValueSize != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.ValueSize))
		i--
		dAtA[i] = 0x18
	}
	if m.KeySize != 0 {
		i = encodeVarintHashmap(dAtA, i, uint64(m.KeySize))
		i--
		dAtA[i] = 0x10
	}
	if m.KeySum != 0 {
		i -= 8
		encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(m.KeySum))
		i--
		dAtA[i] = 0x9
	}
	return len(dAtA) - i, nil
}

func encodeVarintHashmap(dAtA []byte, offset int, v uint64) int {
	offset -= sovHashmap(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *HashMapInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlotDirsAddr != 0 {
		n += 1 + sovHashmap(uint64(m.SlotDirsAddr))
	}
	if m.SlotDirCount != 0 {
		n += 1 + sovHashmap(uint64(m.SlotDirCount))
	}
	if m.MaxSlotDirCountShift != 0 {
		n += 1 + sovHashmap(uint64(m.MaxSlotDirCountShift))
	}
	if m.SlotCount != 0 {
		n += 1 + sovHashmap(uint64(m.SlotCount))
	}
	if m.MinSlotCountShift != 0 {
		n += 1 + sovHashmap(uint64(m.MinSlotCountShift))
	}
	if m.ItemCount != 0 {
		n += 1 + sovHashmap(uint64(m.ItemCount))
	}
	if m.PayloadSize != 0 {
		n += 1 + sovHashmap(uint64(m.PayloadSize))
	}
	return n
}

func (m *HashSlot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ItemInfos) > 0 {
		for _, e := range m.ItemInfos {
			l = e.Size()
			n += 1 + l + sovHashmap(uint64(l))
		}
	}
	l = m.Bin.Size()
	n += 1 + l + sovHashmap(uint64(l))
	return n
}

func (m *HashItemInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.KeySum != 0 {
		n += 9
	}
	if m.KeySize != 0 {
		n += 1 + sovHashmap(uint64(m.KeySize))
	}
	if m.ValueSize != 0 {
		n += 1 + sovHashmap(uint64(m.ValueSize))
	}
	return n
}

func sovHashmap(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHashmap(x uint64) (n int) {
	return sovHashmap(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *HashMapInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHashmap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashMapInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashMapInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotDirsAddr", wireType)
			}
			m.SlotDirsAddr = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotDirsAddr |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotDirCount", wireType)
			}
			m.SlotDirCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotDirCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSlotDirCountShift", wireType)
			}
			m.MaxSlotDirCountShift = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSlotDirCountShift |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlotCount", wireType)
			}
			m.SlotCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlotCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSlotCountShift", wireType)
			}
			m.MinSlotCountShift = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinSlotCountShift |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemCount", wireType)
			}
			m.ItemCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ItemCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadSize", wireType)
			}
			m.PayloadSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayloadSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHashmap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHashmap
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHashmap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashSlot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHashmap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashSlot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashSlot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ItemInfos", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHashmap
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHashmap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ItemInfos = append(m.ItemInfos, HashItemInfo{})
			if err := m.ItemInfos[len(m.ItemInfos)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bin", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHashmap
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHashmap
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHashmap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHashmap
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHashmap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HashItemInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHashmap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HashItemInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HashItemInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeySum", wireType)
			}
			m.KeySum = 0
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			m.KeySum = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeySize", wireType)
			}
			m.KeySize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KeySize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValueSize", wireType)
			}
			m.ValueSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValueSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHashmap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthHashmap
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthHashmap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHashmap(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHashmap
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHashmap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHashmap
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHashmap
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHashmap
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHashmap        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHashmap          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHashmap = fmt.Errorf("proto: unexpected end of group")
)
